-- PROVICA V3: ejecutar UNA VEZ después de V2.
drop policy if exists "admin_ops_insert_clients" on public.clients;create policy "admin_ops_insert_clients" on public.clients for insert to authenticated with check(public.current_user_role() in ('ADMIN','OPERACIONES'));
drop policy if exists "admin_ops_update_clients" on public.clients;create policy "admin_ops_update_clients" on public.clients for update to authenticated using(public.current_user_role() in ('ADMIN','OPERACIONES')) with check(public.current_user_role() in ('ADMIN','OPERACIONES'));
drop policy if exists "admin_ops_insert_sites" on public.sites;create policy "admin_ops_insert_sites" on public.sites for insert to authenticated with check(public.current_user_role() in ('ADMIN','OPERACIONES'));
drop policy if exists "admin_ops_update_sites" on public.sites;create policy "admin_ops_update_sites" on public.sites for update to authenticated using(public.current_user_role() in ('ADMIN','OPERACIONES')) with check(public.current_user_role() in ('ADMIN','OPERACIONES'));
drop policy if exists "admin_ops_insert_posts" on public.guard_posts;create policy "admin_ops_insert_posts" on public.guard_posts for insert to authenticated with check(public.current_user_role() in ('ADMIN','OPERACIONES'));
drop policy if exists "admin_ops_update_posts" on public.guard_posts;create policy "admin_ops_update_posts" on public.guard_posts for update to authenticated using(public.current_user_role() in ('ADMIN','OPERACIONES')) with check(public.current_user_role() in ('ADMIN','OPERACIONES'));
drop policy if exists "staff_read_profiles" on public.profiles;create policy "staff_read_profiles" on public.profiles for select to authenticated using(id=auth.uid() or public.current_user_role() in ('ADMIN','RRHH','OPERACIONES','SUPERVISOR'));
alter table public.audit_log enable row level security;drop policy if exists "admin_read_audit" on public.audit_log;create policy "admin_read_audit" on public.audit_log for select to authenticated using(public.current_user_role()='ADMIN');
