'use client'
import {useState} from 'react';import {createClient} from '../lib/supabase/client'
const local=(iso:string)=>{const d=new Date(iso),p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
const hours=(a:string,b:string)=>(new Date(b).getTime()-new Date(a).getTime())/3600000
export default function ShiftManager({posts,guards,shifts}:{posts:any[],guards:any[],shifts:any[]}){
 const[p,setP]=useState(posts[0]?.id||''),[g,setG]=useState(guards[0]?.id||''),[a,setA]=useState(''),[dur,setDur]=useState(12),[m,setM]=useState(''),[edit,setEdit]=useState<any>(null)
 const s=createClient()
 async function overlap(guard:string,A:Date,B:Date,ignore?:string){let q=s.from('shifts').select('id').eq('guard_id',guard).neq('status','CANCELADO').lt('starts_at',B.toISOString()).gt('ends_at',A.toISOString());if(ignore)q=q.neq('id',ignore);return await q.limit(1)}
 async function create(e:React.FormEvent){e.preventDefault();setM('');const A=new Date(a),B=new Date(A.getTime()+dur*3600000);const{data:o,error}=await overlap(g,A,B);if(error){setM(error.message);return}if(o?.length){setM('El guardia ya tiene un turno superpuesto.');return}const{x:error2}= {x:(await s.from('shifts').insert({guard_post_id:p,guard_id:g,starts_at:A.toISOString(),ends_at:B.toISOString(),status:'PROGRAMADO'})).error};if(error2)setM(error2.message);else location.reload()}
 async function save(){const A=new Date(edit.starts_at),B=new Date(edit.ends_at),h=hours(edit.starts_at,edit.ends_at);if(B<=A||![8,12].includes(h)){setM('La jornada debe ser exactamente de 8 o 12 horas.');return}const{data:o,error}=await overlap(edit.guard_id,A,B,edit.id);if(error){setM(error.message);return}if(o?.length){setM('El guardia ya tiene un turno superpuesto.');return}const{error:u}=await s.from('shifts').update({guard_post_id:edit.guard_post_id,guard_id:edit.guard_id,starts_at:A.toISOString(),ends_at:B.toISOString()}).eq('id',edit.id);if(u)setM(u.message);else location.reload()}
 async function remove(x:any){if(!confirm('¿Eliminar este turno? Esta acción solo debe usarse antes de que exista asistencia asociada.'))return;const{error}=await s.from('shifts').delete().eq('id',x.id);if(error){if(confirm('No se pudo eliminar. ¿Desea marcarlo como CANCELADO?')){const{error:e}=await s.from('shifts').update({status:'CANCELADO'}).eq('id',x.id);if(e)setM(e.message);else location.reload()}else setM(error.message)}else location.reload()}
 const state=(x:any)=>x.status==='CANCELADO'?'CANCELADO':Date.now()<new Date(x.starts_at).getTime()?'PROGRAMADO':Date.now()>=new Date(x.ends_at).getTime()?'FINALIZADO':'EN CURSO'
 return <><div className="panel"><h3>Programar turno</h3><p>Seleccione inicio y jornada. El fin se calcula automáticamente. Solo se permiten jornadas de 8 o 12 horas.</p><form className="form" onSubmit={create}><select value={p} onChange={e=>setP(e.target.value)} required>{posts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={g} onChange={e=>setG(e.target.value)} required>{guards.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><label>Inicio<input type="datetime-local" value={a} onChange={e=>setA(e.target.value)} required/></label><label>Jornada<select value={dur} onChange={e=>setDur(+e.target.value)}><option value={8}>8 horas</option><option value={12}>12 horas</option></select></label><button>Programar turno</button></form>{a&&<p><b>Fin calculado:</b> {new Date(new Date(a).getTime()+dur*3600000).toLocaleString('es-EC')}</p>}{m&&<p className="error">{m}</p>}</div>
 <div className="panel"><h3>Turnos</h3><table><thead><tr><th>Cliente</th><th>Puesto</th><th>Guardia</th><th>Inicio</th><th>Fin</th><th>Horas</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{shifts.map((x:any)=><tr key={x.id}><td>{x.guard_posts?.sites?.clients?.name||'-'}</td><td>{x.guard_posts?.name||'-'}</td><td>{x.profiles?.full_name||'-'}</td><td>{new Date(x.starts_at).toLocaleString('es-EC')}</td><td>{new Date(x.ends_at).toLocaleString('es-EC')}</td><td>{hours(x.starts_at,x.ends_at).toFixed(0)} h</td><td>{state(x)}</td><td><button className="small secondary" onClick={()=>setEdit({...x,starts_at:local(x.starts_at),ends_at:local(x.ends_at)})}>Editar</button> <button className="small danger" onClick={()=>remove(x)}>Eliminar</button></td></tr>)}</tbody></table></div>
 {edit&&<div className="modal"><div className="modal-card"><h3>Editar turno</h3><div className="form"><select value={edit.guard_post_id} onChange={e=>setEdit({...edit,guard_post_id:e.target.value})}>{posts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={edit.guard_id} onChange={e=>setEdit({...edit,guard_id:e.target.value})}>{guards.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><label>Inicio<input type="datetime-local" value={edit.starts_at} onChange={e=>setEdit({...edit,starts_at:e.target.value})}/></label><label>Fin<input type="datetime-local" value={edit.ends_at} onChange={e=>setEdit({...edit,ends_at:e.target.value})}/></label></div><p>Duración: {hours(edit.starts_at,edit.ends_at).toFixed(1)} h (debe ser 8 o 12)</p><button onClick={save}>Guardar cambios</button> <button className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></div></div>}</>}
