'use client'
import {useMemo,useState} from 'react';import {createClient} from '../lib/supabase/client'
const local=(iso:string)=>{const d=new Date(iso),p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
const hours=(a:string,b:string)=>(new Date(b).getTime()-new Date(a).getTime())/3600000
export default function ShiftManager({posts,guards,shifts}:{posts:any[],guards:any[],shifts:any[]}){
 const clients=useMemo(()=>Array.from(new Map(posts.map((x:any)=>[x.sites?.clients?.id,x.sites?.clients])).values()).filter(Boolean),[posts])
 const[c,setC]=useState<any>(clients[0]?.id||'');const sites=useMemo(()=>Array.from(new Map(posts.filter((x:any)=>x.sites?.clients?.id===c).map((x:any)=>[x.sites?.id,x.sites])).values()).filter(Boolean),[posts,c])
 const[site,setSite]=useState<any>(sites[0]?.id||'');const filtered=useMemo(()=>posts.filter((x:any)=>x.sites?.id===site),[posts,site])
 const[p,setP]=useState<any>(filtered[0]?.id||''),[g,setG]=useState(guards[0]?.id||''),[a,setA]=useState(''),[dur,setDur]=useState(12),[m,setM]=useState(''),[edit,setEdit]=useState<any>(null);const s=createClient()
 function chooseClient(v:string){setC(v);const ss=Array.from(new Map(posts.filter((x:any)=>x.sites?.clients?.id===v).map((x:any)=>[x.sites?.id,x.sites])).values()).filter(Boolean) as any[];setSite(ss[0]?.id||'');setP(posts.find((x:any)=>x.sites?.id===ss[0]?.id)?.id||'')}
 function chooseSite(v:string){setSite(v);setP(posts.find((x:any)=>x.sites?.id===v)?.id||'')}
 async function overlap(guard:string,A:Date,B:Date,ignore?:string){let q=s.from('shifts').select('id').eq('guard_id',guard).neq('status','CANCELADO').lt('starts_at',B.toISOString()).gt('ends_at',A.toISOString());if(ignore)q=q.neq('id',ignore);return await q.limit(1)}
 async function create(e:React.FormEvent){e.preventDefault();setM('');if(!p||!g){setM('Seleccione cliente, instalación, puesto y guardia.');return}const A=new Date(a),B=new Date(A.getTime()+dur*3600000);const{data:o,error}=await overlap(g,A,B);if(error){setM(error.message);return}if(o?.length){setM('El guardia ya tiene un turno superpuesto.');return}const{error:e2}=await s.from('shifts').insert({guard_post_id:p,guard_id:g,starts_at:A.toISOString(),ends_at:B.toISOString(),status:'PROGRAMADO'});if(e2)setM(e2.message);else location.reload()}
 async function save(){const A=new Date(edit.starts_at),B=new Date(edit.ends_at),h=hours(edit.starts_at,edit.ends_at);if(B<=A||![8,12].includes(h)){setM('La jornada debe ser exactamente de 8 o 12 horas.');return}const{data:o,error}=await overlap(edit.guard_id,A,B,edit.id);if(error){setM(error.message);return}if(o?.length){setM('El guardia ya tiene un turno superpuesto.');return}const{error:u}=await s.from('shifts').update({guard_post_id:edit.guard_post_id,guard_id:edit.guard_id,starts_at:A.toISOString(),ends_at:B.toISOString()}).eq('id',edit.id);if(u)setM(u.message);else location.reload()}
 async function remove(x:any){if(!confirm('¿Eliminar este turno?'))return;const{error}=await s.from('shifts').delete().eq('id',x.id);if(error){if(confirm('No se pudo eliminar. ¿Marcarlo como CANCELADO?')){const{error:e}=await s.from('shifts').update({status:'CANCELADO'}).eq('id',x.id);if(e)setM(e.message);else location.reload()}else setM(error.message)}else location.reload()}
 const state=(x:any)=>x.status==='CANCELADO'?'CANCELADO':Date.now()<new Date(x.starts_at).getTime()?'PROGRAMADO':Date.now()>=new Date(x.ends_at).getTime()?'FINALIZADO':'EN CURSO'
 return <><div className="panel"><h3>Programar turno</h3><p>Seleccione Cliente → Instalación → Puesto → Guardia. El fin se calcula automáticamente.</p>{!posts.length&&<p className="error">No existen puestos activos asociados a clientes e instalaciones activas.</p>}<form className="form" onSubmit={create}>
 <label>Cliente<select value={c} onChange={e=>chooseClient(e.target.value)} required><option value="">Seleccione cliente</option>{clients.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>Instalación<select value={site} onChange={e=>chooseSite(e.target.value)} required><option value="">Seleccione instalación</option>{sites.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>Puesto<select value={p} onChange={e=>setP(e.target.value)} required><option value="">Seleccione puesto</option>{filtered.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>Guardia<select value={g} onChange={e=>setG(e.target.value)} required><option value="">Seleccione guardia</option>{guards.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label>
 <label>Inicio<input type="datetime-local" value={a} onChange={e=>setA(e.target.value)} required/></label><label>Jornada<select value={dur} onChange={e=>setDur(+e.target.value)}><option value={8}>8 horas</option><option value={12}>12 horas</option></select></label><button>Programar turno</button></form>{a&&<p><b>Fin calculado:</b> {new Date(new Date(a).getTime()+dur*3600000).toLocaleString('es-EC')}</p>}{m&&<p className="error">{m}</p>}</div>
 <div className="panel"><h3>Turnos</h3><table><thead><tr><th>Cliente</th><th>Instalación</th><th>Puesto</th><th>Guardia</th><th>Inicio</th><th>Fin</th><th>Horas</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{shifts.map((x:any)=><tr key={x.id}><td>{x.guard_posts?.sites?.clients?.name||'-'}</td><td>{x.guard_posts?.sites?.name||'-'}</td><td>{x.guard_posts?.name||'-'}</td><td>{x.profiles?.full_name||'-'}</td><td>{new Date(x.starts_at).toLocaleString('es-EC')}</td><td>{new Date(x.ends_at).toLocaleString('es-EC')}</td><td>{hours(x.starts_at,x.ends_at).toFixed(0)} h</td><td>{state(x)}</td><td><button className="small secondary" onClick={()=>setEdit({...x,starts_at:local(x.starts_at),ends_at:local(x.ends_at)})}>Editar</button> <button className="small danger" onClick={()=>remove(x)}>Eliminar</button></td></tr>)}</tbody></table></div>
 {edit&&<div className="modal"><div className="modal-card"><h3>Editar turno</h3><div className="form"><label>Puesto<select value={edit.guard_post_id} onChange={e=>setEdit({...edit,guard_post_id:e.target.value})}>{posts.map((x:any)=><option key={x.id} value={x.id}>{x.sites?.clients?.name} / {x.sites?.name} / {x.name}</option>)}</select></label><label>Guardia<select value={edit.guard_id} onChange={e=>setEdit({...edit,guard_id:e.target.value})}>{guards.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Inicio<input type="datetime-local" value={edit.starts_at} onChange={e=>setEdit({...edit,starts_at:e.target.value})}/></label><label>Fin<input type="datetime-local" value={edit.ends_at} onChange={e=>setEdit({...edit,ends_at:e.target.value})}/></label></div><p>Duración: {hours(edit.starts_at,edit.ends_at).toFixed(1)} h</p><button onClick={save}>Guardar cambios</button> <button className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></div></div>}</>}
